name: Uno Build and Pack

on:
  push:
    branches:
    - uno-platform
    paths:
    - '**.csproj'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Add GitHub Packages for Nuget
      run: nuget sources add -Source https://nuget.pkg.github.com/bassclefstudio/index.json -Name "GPR" -Username bassclefstudio -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
    - name: MSBuild
      run: msbuild BassClefStudio.UWP.sln -t:build -p:Configuration=Debug -p:Platform="Any CPU" -m -restore
    - name: Pack
      run: dotnet pack --configuration Debug
    - name: Push
      run: dotnet nuget push "**.nupkg" --source "GPR" --skip-duplicate